### PR TITLE
rules: add zoom.rules

### PR DESCRIPTION
**Pull request by kfeoktistoff**

### CODE REVIEW

**Comment by Atrate** [comment]
I think this should be `chat`, not `lowlatency_rt`. See https://github.com/Nefelim4ag/Ananicy/blob/master/ananicy.d/00-default/discord.rules for an example.

**Comment by kfeoktistoff** [comment]
> I think this should be `chat`, not `lowlatency_rt`. See https://github.com/Nefelim4ag/Ananicy/blob/master/ananicy.d/00-default/discord.rules for an example.

What about video calls and screen sharing? As far as I understand, such functionality requires real time video processing and it was the reason why I decided to use `lowlatency_rt`. Please correct me if I'm wrong.

**Comment by Nightbane112** [comment]
> What about video calls and screen sharing? As far as I understand, such functionality requires real time video processing and it was the reason why I decided to use `lowlatency_rt`. Please correct me if I'm wrong.

Personally, I wouldn't recommend using `lowlatency_rt` unless you are doing something that is latency-sensitive like for example music recording or on systems that have a hard deadline to occur.

On video calls & screen sharing, I highly doubt that apps like Discord or Zoom **need** realtime privileges. It would make sense for these kinds of apps to have some built-in latency compensation system for this usecase.  If you have to rely on this, you probably have bigger problems at hand.

**Comment by kfeoktistoff** [comment]
> > What about video calls and screen sharing? As far as I understand, such functionality requires real time video processing and it was the reason why I decided to use `lowlatency_rt`. Please correct me if I'm wrong.
> 
> Personally, I wouldn't recommend using `lowlatency_rt` unless you are doing something that is latency-sensitive like for example music recording or on systems that have a hard deadline to occur.
> 
> On video calls & screen sharing, I highly doubt that apps like Discord or Zoom **need** realtime privileges. It would make sense for these kinds of apps to have some built-in latency compensation system for this usecase. If you have to rely on this, you probably have bigger problems at hand.

Thanks for explanation, the PR updated!

**Pull request merged**
