### PR TITLE
Do not print IONICE/IOCLASS warning for bfq-mq

### PR DESCRIPTION
**Pull request by terencode**
bfq-mq can support them:
CONFIG_MQ_IOSCHED_BFQ=y
CONFIG_MQ_BFQ_GROUP_IOSCHED=y

### CODE REVIEW

**Comment by Nefelim4ag** [comment]
@terencode, sorry but where you found bfq-mq?
i.e. in kernel (mainline) bfq:
```
~ grep . /sys/class/block/sda/queue/scheduler 
mq-deadline kyber [bfq] none
```

**Comment by terencode** [comment]
I'm using [linux-ck](https://aur.archlinux.org/packages/linux-ck) from AUR but I think bfq-mq is now mainlined into the kernel but not enabled by default.

**Comment by terencode** [comment]
I found the relevant commit: https://github.com/torvalds/linux/commit/694752922b12bd318aa80191bd9d8c3dcfb39055

**Comment by Nefelim4ag** [comment]
@terencode, i mean that in mainline kernel it's named as just bfq, not bfq-mq.

**Comment by Nefelim4ag** [comment]
Doesn't matter, if this shut up warning for you, merged.

**Comment by terencode** [comment]
@Nefelim4ag I have both bfq and bfq-mq.

**Pull request merged**
