### PR TITLE
Update _steam.rules

### PR DESCRIPTION
**Pull request by shoober420**

### CODE REVIEW

**Comment by Nefelim4ag** [comment]
Are you really play all of that games? :)
You created more then 60 pull requests :D

**Comment by shoober420** [comment]
I don’t own all of these games, but I added them because I thought of others who may have them :)

I do own over 500 games on Steam though lol :D

**Comment by Nefelim4ag** [comment]
I will merge everything just because you already did some work on it, but i'm really not sure that we didn't have overlaps in binary names and that will really needed.
I mean, i expect that people write rules for her own needs, and if they helps - send PR

**Comment by shoober420** [comment]
I’ll double check and see if there are duplicates. There might be some in the wine directory for games files named “game.exe”.

**Comment by shoober420** [comment]
Duplicates found and fixed.

I should mention I own a good 95% of these games I commit. I would add other games from a series just for completeness. The GTA, LEGO, and Ys series and good examples.

**Pull request merged**
